#!/usr/bin/env bash
echo 'Selam all!';

i=0; until [ $i -ge 2 ]; do echo 'Hi Aby!'; ((i++)); done

i=0; while [ $i -le 1 ]; do echo 'Hey Mark!'; ((i++)); done

for i in i [0..1]
do
    echo 'Hello Fistum!'
done




