#!/usr/bin/env bash
echo 'Hello Fistum!';

i=0; while [ $i -le 2 ]; do echo 'I am proud of you!'; ((i++)); done

i=0; until [ $i -ge 3 ]; do echo 'Just dream big dude!'; ((i++)); done


for i in [ 0..2 ]
do
    echo 'You are wonderfull!'
done